### ISSUE TITLE
Does not work when installed on a system

### ISSUE THREAD

**Issue by quozl** [sugarlabs/flappy#23]
```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/FlappyBirds.activity/main.py", line 149, in make
    self.birds.jump(land1, land2, self.land1x, self.land2x, self)
  File "/usr/share/sugar/activities/FlappyBirds.activity/elements.py", line 136, in jump
    b.run(g.gameDisplay, g.scores)
  File "/usr/share/sugar/activities/FlappyBirds.activity/scorescreen.py", line 61, in run
    open('score.pkl','w+')
IOError: [Errno 13] Permission denied: 'score.pkl'
```

**Comment by quozl** [comment]
* [ ] apply the changes to score file path found in Stick Hero commits.

**Comment by quozl** [comment]
https://github.com/sugarlabs/stick-hero-activity/commit/eb5fd8e5d6dd8c5000c2713ae37788aafd264bd1

**Comment by chimosky** [comment]
Closing as issue has been transferred.

**Comment by Dimi20cen** [comment]
Flappy doesn't create a file to store high score. Therefore this issue is not present here
