### ISSUE TITLE
Error, video system not initialized

### ISSUE THREAD

**Issue by quozl** [sugarlabs/flappy#4]
@zeecoder606, this error is in logs;

```
Traceback (most recent call last):
  File "/home/guest/Activities/Flappy.activity/sugargame/event.py", line 224, in _mousemove_cb
    self._post(evt)
  File "/home/guest/Activities/Flappy.activity/sugargame/event.py", line 258, in _post
    raise e
pygame.error: video system not initialized
```

**Comment by rhl-bthr** [comment]
@quozl, I was unable to reproduce this during #8

Kindly review this issue

**Comment by quozl** [comment]
Yes, new version of Sugargame should have fixed it.  To verify, you would have had to check out the version before the Sugargame upgrade, and compare the traceback line numbers against the source.

**Comment by rhl-bthr** [comment]
Verified. Thank you
